/* Generated By:JJTree: Do not edit this line. ASTNumberLiteral.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package edu.sru.andgate.bitbot.parser;

public
class ASTNumberLiteral extends SimpleNode {
  public ASTNumberLiteral(int id) {
    super(id);
  }

  public ASTNumberLiteral(bc1 p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(bc1Visitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=979df925fc756c2e2ebf8fac4c622f72 (do not edit this line) */
