/* Generated By:JJTree: Do not edit this line. ASTStringConcatenation.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package edu.sru.andgate.bitbot.parser;

public
class ASTStringConcatenation extends SimpleNode {
  public ASTStringConcatenation(int id) {
    super(id);
  }

  public ASTStringConcatenation(bc1 p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(bc1Visitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=d9c3debf71e02d28dadcaaa7b2fe7e1f (do not edit this line) */
