/* Generated By:JJTree: Do not edit this line. ASTSubDeclaration.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package edu.sru.andgate.bitbot.parser;

public
class ASTSubDeclaration extends SimpleNode {
  public ASTSubDeclaration(int id) {
    super(id);
  }

  public ASTSubDeclaration(bc1 p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(bc1Visitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=00a08d8d6a678a8349ffbf1e498f6fcb (do not edit this line) */
