/* Generated By:JJTree: Do not edit this line. ASTWhileLoop.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package edu.sru.andgate.bitbot.parser;

public
class ASTWhileLoop extends SimpleNode {
  public ASTWhileLoop(int id) {
    super(id);
  }

  public ASTWhileLoop(bc1 p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(bc1Visitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=59ed97a6fed4ff771be2c416047ea6b2 (do not edit this line) */
