/* Generated By:JJTree&JavaCC: Do not edit this line. bc1Constants.java */
package edu.sru.andgate.bitbot.parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface bc1Constants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int NUMBER = 3;
  /** RegularExpression Id. */
  int NUMBER_EL = 4;
  /** RegularExpression Id. */
  int BOOL_OP = 5;
  /** RegularExpression Id. */
  int EQ_OP = 6;
  /** RegularExpression Id. */
  int REL_OP = 7;
  /** RegularExpression Id. */
  int ADD_OP = 8;
  /** RegularExpression Id. */
  int MUL_OP = 9;
  /** RegularExpression Id. */
  int CONCAT = 10;
  /** RegularExpression Id. */
  int NL = 11;
  /** RegularExpression Id. */
  int PRINT = 12;
  /** RegularExpression Id. */
  int LET = 13;
  /** RegularExpression Id. */
  int EQUAL = 14;
  /** RegularExpression Id. */
  int DIM = 15;
  /** RegularExpression Id. */
  int AS = 16;
  /** RegularExpression Id. */
  int WHILE = 17;
  /** RegularExpression Id. */
  int DO = 18;
  /** RegularExpression Id. */
  int LOOP = 19;
  /** RegularExpression Id. */
  int FOR = 20;
  /** RegularExpression Id. */
  int TO = 21;
  /** RegularExpression Id. */
  int STEP = 22;
  /** RegularExpression Id. */
  int NEXT = 23;
  /** RegularExpression Id. */
  int IF = 24;
  /** RegularExpression Id. */
  int THEN = 25;
  /** RegularExpression Id. */
  int ELSE = 26;
  /** RegularExpression Id. */
  int ENDIF = 27;
  /** RegularExpression Id. */
  int INTEGER = 28;
  /** RegularExpression Id. */
  int DOUBLE = 29;
  /** RegularExpression Id. */
  int STRING = 30;
  /** RegularExpression Id. */
  int ARRAY = 31;
  /** RegularExpression Id. */
  int SUBROUTINE = 32;
  /** RegularExpression Id. */
  int WITH = 33;
  /** RegularExpression Id. */
  int CALL = 34;
  /** RegularExpression Id. */
  int END = 35;
  /** RegularExpression Id. */
  int RETURN = 36;
  /** RegularExpression Id. */
  int IDENTIFIER = 37;
  /** RegularExpression Id. */
  int LETTER = 38;
  /** RegularExpression Id. */
  int DIGIT = 39;
  /** RegularExpression Id. */
  int STRING_LITERAL = 40;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "<NUMBER>",
    "<NUMBER_EL>",
    "<BOOL_OP>",
    "<EQ_OP>",
    "<REL_OP>",
    "<ADD_OP>",
    "<MUL_OP>",
    "\"&\"",
    "<NL>",
    "\"print\"",
    "\"let\"",
    "<EQUAL>",
    "\"dim\"",
    "\"as\"",
    "\"while\"",
    "\"do\"",
    "\"loop\"",
    "\"for\"",
    "\"to\"",
    "\"step\"",
    "\"next\"",
    "\"if\"",
    "\"then\"",
    "\"else\"",
    "\"endif\"",
    "\"integer\"",
    "\"double\"",
    "\"string\"",
    "\"array\"",
    "<SUBROUTINE>",
    "\"with\"",
    "\"call\"",
    "\"end\"",
    "\"return\"",
    "<IDENTIFIER>",
    "<LETTER>",
    "<DIGIT>",
    "<STRING_LITERAL>",
    "\"(\"",
    "\")\"",
    "\",\"",
  };

}
