/* Generated By:JJTree&JavaCC: Do not edit this line. bc1Constants.java */
package edu.sru.andgate.bitbot.parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface bc1Constants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int INTEGER_LITERAL = 5;
  /** RegularExpression Id. */
  int DECIMAL_LITERAL = 6;
  /** RegularExpression Id. */
  int HEX_LITERAL = 7;
  /** RegularExpression Id. */
  int OCTAL_LITERAL = 8;
  /** RegularExpression Id. */
  int BOOL_OP = 9;
  /** RegularExpression Id. */
  int EQ_OP = 10;
  /** RegularExpression Id. */
  int REL_OP = 11;
  /** RegularExpression Id. */
  int ADD_OP = 12;
  /** RegularExpression Id. */
  int MUL_OP = 13;
  /** RegularExpression Id. */
  int CONCAT = 14;
  /** RegularExpression Id. */
  int NL = 15;
  /** RegularExpression Id. */
  int PRINT = 16;
  /** RegularExpression Id. */
  int LET = 17;
  /** RegularExpression Id. */
  int EQUAL = 18;
  /** RegularExpression Id. */
  int DIM = 19;
  /** RegularExpression Id. */
  int AS = 20;
  /** RegularExpression Id. */
  int WHILE = 21;
  /** RegularExpression Id. */
  int DO = 22;
  /** RegularExpression Id. */
  int LOOP = 23;
  /** RegularExpression Id. */
  int FOR = 24;
  /** RegularExpression Id. */
  int TO = 25;
  /** RegularExpression Id. */
  int STEP = 26;
  /** RegularExpression Id. */
  int NEXT = 27;
  /** RegularExpression Id. */
  int IF = 28;
  /** RegularExpression Id. */
  int THEN = 29;
  /** RegularExpression Id. */
  int ELSE = 30;
  /** RegularExpression Id. */
  int ENDIF = 31;
  /** RegularExpression Id. */
  int INTEGER = 32;
  /** RegularExpression Id. */
  int DOUBLE = 33;
  /** RegularExpression Id. */
  int STRING = 34;
  /** RegularExpression Id. */
  int ARRAY = 35;
  /** RegularExpression Id. */
  int PROGRAM = 36;
  /** RegularExpression Id. */
  int SUBROUTINE = 37;
  /** RegularExpression Id. */
  int CALL = 38;
  /** RegularExpression Id. */
  int END = 39;
  /** RegularExpression Id. */
  int IDENTIFIER = 40;
  /** RegularExpression Id. */
  int LETTER = 41;
  /** RegularExpression Id. */
  int DIGIT = 42;
  /** RegularExpression Id. */
  int STRING_LITERAL = 43;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "<token of kind 3>",
    "<token of kind 4>",
    "<INTEGER_LITERAL>",
    "<DECIMAL_LITERAL>",
    "<HEX_LITERAL>",
    "<OCTAL_LITERAL>",
    "<BOOL_OP>",
    "<EQ_OP>",
    "<REL_OP>",
    "<ADD_OP>",
    "<MUL_OP>",
    "\"&\"",
    "<NL>",
    "\"print\"",
    "\"let\"",
    "<EQUAL>",
    "\"dim\"",
    "\"as\"",
    "\"while\"",
    "\"do\"",
    "\"loop\"",
    "\"for\"",
    "\"to\"",
    "\"step\"",
    "\"next\"",
    "\"if\"",
    "\"then\"",
    "\"else\"",
    "\"endif\"",
    "\"integer\"",
    "\"double\"",
    "\"string\"",
    "\"array\"",
    "\"program\"",
    "<SUBROUTINE>",
    "\"call\"",
    "\"end\"",
    "<IDENTIFIER>",
    "<LETTER>",
    "<DIGIT>",
    "<STRING_LITERAL>",
    "\"(\"",
    "\")\"",
    "\",\"",
  };

}
