/* Generated By:JavaCC: Do not edit this line. bc1TreeConstants.java Version 5.0 */
package edu.sru.andgate.bitbot.parser;

public interface bc1TreeConstants
{
  public int JJTROOT = 0;
  public int JJTPROGRAM = 1;
  public int JJTVOID = 2;
  public int JJTPRINT = 3;
  public int JJTDECLARATION = 4;
  public int JJTASSIGNMENT = 5;
  public int JJTSTRINGEXPRESSION = 6;
  public int JJTSTRINGLITERAL = 7;
  public int JJTBOOLEANEXPRESSION = 8;
  public int JJTEQUALITYEXPRESSION = 9;
  public int JJTRELATIONALEXPRESSION = 10;
  public int JJTADDITIVEEXPRESSION = 11;
  public int JJTMULTIPLICATIVEEXPRESSION = 12;
  public int JJTUNARYEXPRESSION = 13;
  public int JJTIDENTIFIER = 14;
  public int JJTINTEGERLITERAL = 15;


  public String[] jjtNodeName = {
    "Root",
    "Program",
    "void",
    "Print",
    "Declaration",
    "Assignment",
    "StringExpression",
    "StringLiteral",
    "BooleanExpression",
    "EqualityExpression",
    "RelationalExpression",
    "AdditiveExpression",
    "MultiplicativeExpression",
    "UnaryExpression",
    "Identifier",
    "IntegerLiteral",
  };
}
/* JavaCC - OriginalChecksum=9b546a8f037b69bd0b6c201a7459ed56 (do not edit this line) */
