/* Generated By:JavaCC: Do not edit this line. bc1Visitor.java Version 5.0 */
package edu.sru.andgate.bitbot.parser;

public interface bc1Visitor
{
  public Object visit(SimpleNode node, Object data);
  public Object visit(ASTRoot node, Object data);
  public Object visit(ASTProgram node, Object data);
  public Object visit(ASTListOfInstructions node, Object data);
  public Object visit(ASTWhileLoop node, Object data);
  public Object visit(ASTIfStatement node, Object data);
  public Object visit(ASTForLoop node, Object data);
  public Object visit(ASTSubCall node, Object data);
  public Object visit(ASTSubDef node, Object data);
  public Object visit(ASTPrint node, Object data);
  public Object visit(ASTDeclaration node, Object data);
  public Object visit(ASTAssignment node, Object data);
  public Object visit(ASTConcatExpression node, Object data);
  public Object visit(ASTStringLiteral node, Object data);
  public Object visit(ASTBooleanExpression node, Object data);
  public Object visit(ASTEqualityExpression node, Object data);
  public Object visit(ASTRelationalExpression node, Object data);
  public Object visit(ASTAdditiveExpression node, Object data);
  public Object visit(ASTMultiplicativeExpression node, Object data);
  public Object visit(ASTUnaryExpression node, Object data);
  public Object visit(ASTIdentifier node, Object data);
  public Object visit(ASTNumberLiteral node, Object data);
}
/* JavaCC - OriginalChecksum=da5b257649f19bc0789cdfc3e0bc4c56 (do not edit this line) */
