/* Generated By:JavaCC: Do not edit this line. bc1Visitor.java Version 5.0 */
package edu.sru.andgate.bitbot.parser;

public interface bc1Visitor
{
  public Object visit(SimpleNode node, Object data);
  public Object visit(ASTRoot node, Object data);
  public Object visit(ASTProgram node, Object data);
  public Object visit(ASTPrint node, Object data);
  public Object visit(ASTDeclaration node, Object data);
  public Object visit(ASTAssignment node, Object data);
  public Object visit(ASTStringExpression node, Object data);
  public Object visit(ASTStringLiteral node, Object data);
  public Object visit(ASTBooleanExpression node, Object data);
  public Object visit(ASTEqualityExpression node, Object data);
  public Object visit(ASTRelationalExpression node, Object data);
  public Object visit(ASTAdditiveExpression node, Object data);
  public Object visit(ASTMultiplicativeExpression node, Object data);
  public Object visit(ASTUnaryExpression node, Object data);
  public Object visit(ASTIdentifier node, Object data);
  public Object visit(ASTIntegerLiteral node, Object data);
}
/* JavaCC - OriginalChecksum=0065dfb0946849db466e4c29ccc40ef2 (do not edit this line) */
